# Generated by Django 3.0.8 on 2020-10-02 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoastRoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boastRoast', models.BooleanField(choices=[(True, 'Boast'), (False, 'roast')])),
                ('content', models.CharField(max_length=200, null=True)),
                ('upvote', models.IntegerField(blank=True, default=0, null=True)),
                ('downvote', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
